# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMail',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('People', models.IntegerField(default=1)),
                ('Email', models.EmailField(max_length=254)),
                ('Topic', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=15)),
                ('Message', models.TextField(blank=True, max_length=250)),
            ],
        ),
    ]
